services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  redisinsight:
    image: redis/redisinsight
    ports:
      - "7000:5540"
    volumes:
      - ./redisinsight/data:/data
    depends_on:
      - redis
    